# syntax=docker/dockerfile:1

# -----------------------------
# Stage 1: Install dependencies
# -----------------------------
FROM node:22-slim AS deps
WORKDIR /app

# Copy package manifests first to leverage Docker cache
COPY package.json package-lock.json ./
RUN npm ci

# -----------------------------
# Stage 2: Build the application
# -----------------------------
FROM node:22-slim AS builder
WORKDIR /app

# Copy installed node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy the rest of the source code
COPY . .

# Build the Next.js app.
# Placeholder env vars are supplied inline so Next.js can collect page data.
# Real secrets must be provided at runtime via --env-file or -e flags.
RUN DATABASE_URL=postgresql://placeholder \
    BETTER_AUTH_SECRET=placeholder \
    BETTER_AUTH_URL=http://localhost:3000 \
    NEXT_PUBLIC_BETTER_AUTH_URL=http://localhost:3000 \
    GEMINI_API_KEY=placeholder \
    TAVILY_API_KEY=placeholder \
    npm run build

# -----------------------------
# Stage 3: Production runner
# -----------------------------
FROM node:22-slim AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create a non-root user for security
RUN groupadd --gid 1001 nodejs && \
    useradd --uid 1001 --gid nodejs --shell /bin/false nextjs

# Copy the standalone output generated by Next.js
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# Copy static assets (required for standalone output)
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Copy public assets
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
